---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chuck-says-query
  name: chuck-says-query
spec:
  type: LoadBalancer
  ports:
    - port: 8081         # Puerto externo que expondrá el LoadBalancer.
      protocol: TCP
      targetPort: 48080  # Puerto donde la app escucha dentro del contenedor.
  selector:
    app: chuck-says-query
status:
  loadBalancer: {}
